### PR TITLE
Non-Temporal Memory Transfers for ARM

### PR DESCRIPTION
**Pull request by davschneller**
This PR adds non-temporal loads/stores for ARM processors—both for an AARCH64 and SVE flavor.

### CODE REVIEW

**Comment by krenzland** [comment]
Works on my M2. I tried a convergence test (Snell's law) and achieved the same error for both this branch and master. Performance difference is hart to quantify. As this is a laptop, the difference between runs with the same settings is smaller than the difference between the settings.

**Comment by sebwolf-de** [comment]
@jwjeremy do you have capacity to test this branch and the master branch on your macbook before the training next week?

**Comment by davschneller** [comment]
Just checked on a Grace CPU—the energy results (up to 15 digits) are the same for the noarch, the SVE and the AARCH64 codepath.

**Review by vikaskurapati — APPROVED** [review]
LGTM to as far as I can understand

**Pull request merged**
