### PR TITLE
Added PSpaMM installation to doc

### PR DESCRIPTION
**Pull request by uphoffc**

### CODE REVIEW

**Comment by krenzland** [comment]
Is this actually used for something? Couldn't find anything in documentation or source code.

**Comment by uphoffc** [comment]
Yes, https://github.com/SeisSol/SeisSol/blob/master/generated_code/generate.py#L94

**Comment by krenzland** [comment]
Ah, okay, that's on me.
Still, I'm not sure if adding this as a dependency is the best way here - why not as a submodule?

The other dependencies of this kind make sense as these can be sometimes found on clusters (e.g. hdf5/metis).

**Comment by uphoffc** [comment]
A submodule would also be possible, although I don't like the abuse of submodules as a package manager.

**Comment by krenzland** [comment]
Neither do I.
I'll merge this; but I'm not happy with this.
W should try and find a better solution in the future.

**Comment by uphoffc** [comment]
Yes, but we also should find a solution for a lot of other submodules, like glm, yaml-cpp, maybe ImpalaJIT

-> Package manager that works on hpc clusters

**Pull request merged**
