### PR TITLE
Nothing to be proud of

### PR DESCRIPTION
**Pull request by Thomas-Ulrich**
Commit about the dark side of SeisSol.
The hard-limit on the clustering with attenuation (update of the docu).
The moment rate function files :-)
(I just added a small feature to decrease the size of the concatenated moment rate file, as sampled every 1e-5s over 900s it can be 100mb big).

### CODE REVIEW

**Review by sebwolf-de — APPROVED** [review]
LGTM

**Comment by sebwolf-de** [comment]
There seems to be a problem with libxsmm in the pipeline. @krenzland any ideas?

**Comment by krenzland** [comment]
Not really, no. I'll try to re-trigger it automatically. If that doesn't work, we can pin libxsmm to a working version.

**Comment by krenzland** [comment]
Worked.

**Pull request merged**
