### PR TITLE
update supermuc installation docu

### PR DESCRIPTION
**Pull request by Thomas-Ulrich**
adresses #295?

### CODE REVIEW

**Comment by krenzland** [comment]
Did you test this today? Just asking because they changed some modules around :(

**Comment by Thomas-Ulrich** [comment]
today, yes, but maybe they have made some updates since then. I will test again...

**Comment by Thomas-Ulrich** [comment]
I double-checked, the procedure still works.

**Comment by krenzland** [comment]
Why is this PR updating easi? That includes the checks for NaNs, right=

**Comment by Thomas-Ulrich** [comment]
> Why is this PR updating easi? That includes the checks for NaNs, right?

Hi, because it was never merged (sorry for occulting this change).

**Pull request merged**
