### PR TITLE
Add normalize button to Viewrec

### PR DESCRIPTION
**Pull request by sebwolf-de**
Hi, I have to compare traces of SeisSol with the ones from collaborators who use other codes. Sometimes it is unnecessarily complicated to think about comparisons of magnitudes and we are just interested in the wave form. That's why I added a normalize button to viewrec. Maybe that's useful for the one or other...

### CODE REVIEW

**Comment by krenzland** [comment]
Is normalization by L_inf norm the usual practice?

**Comment by sebwolf-de** [comment]
At least thats what we did for our code comparison

**Comment by krenzland** [comment]
Okay. We can come back to this later if we'd need other norm options.

**Comment by sebwolf-de** [comment]
Yes, you could switch to a Dropdown to distinguish between different norms...

**Pull request merged**
