### PR TITLE
Add option to enable address sanitzer in debug mode

### PR DESCRIPTION
**Pull request by krenzland**
Can use option -DADDRESS_SANITIZER_DEBUG to link with address sanitzer when in debug mode.
https://en.wikipedia.org/wiki/AddressSanitizer can help a lot with finding memory leaks and related issues.

### CODE REVIEW

**Comment by ravil-mobile** [comment]
Do we have lot's memory leaks (Im just asking)? Btw, what is the difference between this tool and valgrind?

**Comment by sebwolf-de** [comment]
Valgrind is an external tool, whereas ASan is directly compiled into your binary.
I've never tried valgrind, since it always took ages to initialize. ASan is much faster to use in that sense.
Also I don't know about valgrind in parallel environments...

**Review by sebwolf-de — APPROVED** [review]
LGTM

**Comment by ravil-mobile** [comment]
@sebwolf-de, thanks for explaining.

> Also I don't know about valgrind in parallel environments...

**Comment by krenzland** [comment]
Address sanitizer can also be a bit annoying with MPI.

**Pull request merged**
