### PR TITLE
Update pointsource.rst

### PR DESCRIPTION
**Pull request by daisy20170101**
update directory to cookbook repo.

### CODE REVIEW

**Comment by sebwolf-de** [comment]
Hi Duo,
thanks for the update. Maybe we should point directly to the file and not just the repo?
Best,
Sebastian

**Comment by krenzland** [comment]
Could you also please clarify, which version of the cookbook is the official one? There's a github and a gitlab version.
Maybe we should consider moving the github repo to the SeisSol organization s,t. it's easier to find?

**Comment by Thomas-Ulrich** [comment]
I did that what @krenzland proposed:
https://github.com/SeisSol/Examples/pull/1
Where can we put the meshes?

**Comment by Thomas-Ulrich** [comment]
deprecated.

**Pull request closed without merging**
