### PR TITLE
Fix A64FX alignment

### PR DESCRIPTION
**Pull request by krenzland**

### CODE REVIEW

**Comment by davschneller** [comment]
This may require https://github.com/SeisSol/yateto/pull/63 at the current moment

**Comment by krenzland** [comment]
Ugh, is yateto's master branch currently broken then? :(

**Comment by davschneller** [comment]
It was an unfortunate consequence of the scalar families patch... :/

**Comment by krenzland** [comment]
No problem, everything should be in working order now :)

**Review by davschneller — APPROVED** [review]

**Pull request merged**
