### PR TITLE
Update xdmf writer.

### PR DESCRIPTION
**Pull request by krenzland**
As mentioned in #330, currently SeisSol fails with a very strange error, when an output file is not found. This PR should address that issue.

### CODE REVIEW

**Review by sebwolf-de — APPROVED** [review]
LGTM, tested with HDF5 and Posix backend.

**Comment by Thomas-Ulrich** [comment]
Cool, thx for fixing that!
Why don't you use in the test the 'parentPath` variable that you just created ;-)

**Comment by ravil-mobile** [comment]
Wait. XdmfWriter CI pipeline got broken: `https://travis-ci.org/github/TUM-I5/XdmfWriter/builds/768393262`

Let's fix it first

**Comment by krenzland** [comment]
Are you going to or should I?
Wasn't aware that we have a pipeline for this :)

(Fix is trivial: Need to use c++17)

**Comment by ravil-mobile** [comment]
I'll fix it.

**Comment by krenzland** [comment]
Thanks, Ravil. I've just noticed that we'll run into problems:

> Using this library may require additional compiler/linker options. GNU implementation prior to 9.1 requires linking with -lstdc++fs and LLVM implementation prior to LLVM 9.0 requires linking with -lc++fs. 

Apparently we need to add additional linker flags to use the fs library. I've used gcc10 locally and thus did not need it.
Not sure whether we need any flags with the Intel compiler. @sebwolf-de did you use intel compiler?

**Comment by sebwolf-de** [comment]
I've used gcc 9.3

**Comment by sebwolf-de** [comment]
It does not compile with Intel 19 though

**Comment by krenzland** [comment]
> It does not compile with Intel 19 though

If you already have the setup, what exactly is the error?

**Comment by sebwolf-de** [comment]
```
/work_fast/ga35kum/SeisSol/master/submodules/xdmfwriter/backends/Base.h(47): catastrophic error: cannot open source file "filesystem"
  #include <filesystem>
                       ^
```

**Comment by krenzland** [comment]
Which gcc modules are loaded?

**Comment by krenzland** [comment]
I've added a commit that adds the necessary flags.

**Review by sebwolf-de — APPROVED** [review]

**Comment by ravil-mobile** [comment]
It is cool that it is working. I knew about `stdc++fs` because I used it for another project. Actually I was surprised at the beginning that you managed to compile seissol without it. But then I assumed that you probably used federa32 with gcc10 and std::filesystem probably became a build-in feature.

**Comment by krenzland** [comment]
Yes, that's exactly it. I'm too used to modern compilers now :)

**Pull request merged**
