### PR TITLE
Demote the error when point sources are not found to a warning

### PR DESCRIPTION
**Pull request by davschneller**
Cf. the discussion in #1212 .

(though maybe it would be better to also specify which point sources were not found then)

### CODE REVIEW

**Comment by Thomas-Ulrich** [comment]
we can close, right?

**Comment by davschneller** [comment]
We can, yes. On the contrary, maybe it would be good to have an error for not-found on-fault receivers as well?

**Comment by Thomas-Ulrich** [comment]
Yes it would probably make sense.

**Comment by davschneller** [comment]
(however, note: it may cause spontaneous errors with receivers on MPI boundaries in some cases)

**Pull request closed without merging**
