### PR TITLE
fix Mw not printed/ print Mw by default

### PR DESCRIPTION
**Pull request by Thomas-Ulrich**
- fix Mw not printed on log when rankDR.NE.0 
- change default  to magnitude_output_on=1

### CODE REVIEW

**Review by sebwolf-de — APPROVED** [review]
Seems good to me :)

**Comment by uphoffc** [comment]
What happens if DR is off or IO%OutputFile is not set?

**Comment by Thomas-Ulrich** [comment]
> What happens if DR is off or IO%OutputFile is not set?
mw is not printed.
https://github.com/SeisSol/SeisSol/blob/master/src/Solver/calc_seissol.f90#L224
the file is named `data-MAG.dat`
https://github.com/SeisSol/SeisSol/blob/master/src/Reader/readpar.f90#L2586

**Comment by uphoffc** [comment]
ok

**Pull request merged**
