### PR TITLE
Implementation of Instantaneous time mirror for SeisSol

### PR DESCRIPTION
**Pull request by vikaskurapati**
Implementation of Instantaneous Time Mirror with three different modes. The following parameters would be needed to in parameters.par to toggle an ITM;

ITMToggle = 1 or 0 //1 switches the ITM on, 0 switches it off
ITMStartingTime // time in simulation when the ITM must be started
ITMTime // duration of ITM
ITMVelocityscalingfactor = scaling factor of velocity depending on the mode of reflection
ITMReflectionType = 1 or 2 or 3 or 4 // 1 reflects both waves, 2 reflects both waves with constant velocity, 3 reflects only P-waves and 4 reflects only S-waves.

### CODE REVIEW

**Comment by davschneller** [comment]
Hi, thanks for the PR! Before (or while) I look at the code, here are some brief general comments from first glance:

* The tests will have to pass; in particular the `clang-format` one (there's also something broken with the anisotropic setup). Also, any new files you add, make sure to add to the formatting list (`.ci/format.sh`), and maybe (though that's non-mandatory) also to the tidying list (`.ci/tidy.sh`).
* You may add the parameters from the PR description to the `Documentation/Parameters.par` file as well.

**Comment by krenzland** [comment]
I can review it but it might be best if @davschneller takes a look as well, as this PR contains some code that I've written myself (and thus shouldn't review).

**Comment by sebwolf-de** [comment]
Just one remark: Since this PR is from Vikas' fork into the main SeisSol repo, the gitlab CI does not run. This is a particular shortcoming of the current CI/CD setup. For now, I suggest that Vikas transfers this branch to the SeisSol/SeisSol repository and then triggers another PR.

**Comment by vikaskurapati** [comment]
Closing this PR as per Sebastian's comments

**Pull request closed without merging**
