### PR TITLE
Ravil/contributing

### PR DESCRIPTION
**Pull request by ravil-mobile**
It is a draft PR. I added a contributing page. In short, I took some bits and pieces from other open source projects. Please, have a look and tell me what I can improve.

*PS* I am sure that there are some typos. I would appreciate you spot them and let me know.

### CODE REVIEW

**Comment by krenzland** [comment]
Thanks, Ravil!
I'll have a look soon. Is it okay if I commit directly to your branch or do you prefer me leaving comments?

**Comment by ravil-mobile** [comment]
> Thanks, Ravil!
> I'll have a look soon. Is it okay if I commit directly to your branch or do you prefer me leaving comments?

Hi, yes sure. It is totally ok

**Comment by ravil-mobile** [comment]
> Maybe we can add "Contribute by feature request issues".

@sebwolf-de, could you suggest which section I shall add it? But `feature request issues` may sound ambiguous. People may think that we will accept only new features, however, we would be glad if users could contribute to bug fixes as well. Therefore, I added the following lines:

> We also recommend to follow a particular format for your branch names i.e., `<prefix>/<short_name>` where `<prefix>` can be *feature*, *bugfix*, *extension*, etc.

I am waiting for @krenzland to merge his PR #300 (code of conduct) with the master. After that, I will make this draft as PR. What do you think? I guess #300 is ready.

**Comment by krenzland** [comment]
Yes, it is ready in my opinion. Still need an approving review.

After that, we can work towards moving this PR. I'd argue that we should do this quickly and then extend it with more comments. E.g. adding a template for feature request issues + mentioning this in the contributions would be a good idea.

**Comment by ravil-mobile** [comment]
> E.g. adding a template for feature request issues + mentioning this in the contributions would be a good idea.

Done! Please, have a look.

**Comment by sebwolf-de** [comment]
I like it that way.

**Comment by ravil-mobile** [comment]
There are 3 different styles: 1) put all markdown files to the root of a project ([pytorch](https://github.com/pytorch/pytorch)) , 2) put to `.github` folder or 3) a mix of them ([bokeh](https://github.com/bokeh/bokeh), [spack](https://github.com/spack/spack)). 

My personal rationale is that I don't want to clutter the root of the project. But I agree with @krenzland  that CoC and License must be in the most visible place i.e., root. So, obviously, I cannot decide which style to stick to. Therefore some of you has to make a decision.

**Comment by krenzland** [comment]
Can we move it to the root for now? If it bothers anyone, we can move it around later with a very small PR.

**Comment by ravil-mobile** [comment]
Ok. I will do it

**Comment by ravil-mobile** [comment]
Done

**Review by sebwolf-de — APPROVED** [review]

**Pull request merged**
