### PR TITLE
exit to MPIABORT

### PR DESCRIPTION
**Pull request by Thomas-Ulrich**
I changed the `call exit(134)` to `call MPI_ABORT(MPI%commWorld, 134)`.
Same files as Sebastian previous PR.
Then I added the `USE mpi_f08` at the beginning of each file modified.
But, then I removed it in files where the compilation was complaining (because MPI_COMM_WORLD was already included in another module?).

(in the process of fixing the compilation, I changed some of the MPI_COMM_WORLD to MPI%commWorld, which should be equivalent, right?).

### CODE REVIEW

**Comment by krenzland** [comment]
In my opinion, we should delete the support for compiling without MPI anyway. Someone is probably going to disagree with that though.

**Comment by krenzland** [comment]
I've had a quick look why the pipeline doesn't compile. It looks like the standard package from ubuntu compiles MPI with an older gfortran. We explictely use a newer gfortran version. So there seems to be a mismatch. Not sure what the solution is. We can try to see whether we can use an older version of gfortran (i.e. the default one that ubuntu ships!). Should work in theory.

@Thomas-Ulrich  Can I commit to your branch? Maybe I can fix it.

**Comment by Thomas-Ulrich** [comment]
Thank you! yes, feel free to commit to the branch!

**Comment by krenzland** [comment]
It's fixed!

**Comment by Thomas-Ulrich** [comment]
Great then it is ready for review too!

**Comment by sebwolf-de** [comment]
>  I changed some of the MPI_COMM_WORLD to MPI%commWorld
I think we should make this consistent.

**Comment by Thomas-Ulrich** [comment]
Hi, 
I've updated most of the MPI_COMM_WORLD to MPI%commWorld, except in 2 files:
src/Numerical_aux/dgbasis.f90
src/Numerical_aux/operators.f90
Because adding the MPI to the function interface would require changing a lot of functions calling these basic functions.

**Review by sebwolf-de — APPROVED** [review]

**Pull request merged**
