### PR TITLE
refactor script

### PR DESCRIPTION
**Pull request by Thomas-Ulrich**
Sorry for the previous pull request (was not clean).

This is a script for generating a vtk coastline file.
I just did some refactoring to be able to apply a translation on the coordinates.
This does not need a thorough review IMO.

### CODE REVIEW

**Comment by sebwolf-de** [comment]
I guess np.savetxt does the same as your for loops...

**Review by sebwolf-de — APPROVED** [review]

**Comment by Thomas-Ulrich** [comment]
> I guess np.savetxt does the same as your for loops...

The updated code uses np.savetxt.
(actually I needed to add the translation vector to the geometry array, so I used numpy instead of lists and then I could use savetxt),

**Comment by krenzland** [comment]
Your code would be clearer if you'd use the following pattern:
```python
with open('pathToFile.ext', 'w') as f:
    f.write(...)
```

This automatically closes the file handle for you - which avoids errors. Probably no need to change here.

**Comment by Thomas-Ulrich** [comment]
thx I will try to remember that.

**Pull request merged**
