### PR TITLE
Fix single precision writers

### PR DESCRIPTION
**Pull request by ravil-mobile**
**Fixed**
- FaultWriter
- WavefieldWriter

**Added**
- Source Code documentation to help to navigate within the code

### CODE REVIEW

**Comment by Thomas-Ulrich** [comment]
I've tested and it seems it does not work (e.g. the fault does not display in paraview).
u v and w are zero in the volume output and surface output.

**Comment by ravil-mobile** [comment]
> I've tested and it seems it does not work (e.g. the fault does not display in paraview).
> u v and w are zero in the volume output and surface output.

Did you compile it using the Release mode? Could you compile it with a debug mode and run it again?

**Comment by ravil-mobile** [comment]
> > I've tested and it seems it does not work (e.g. the fault does not display in paraview).
> > u v and w are zero in the volume output and surface output.
> 
> Did you compile it using the Release mode? Could you compile it with a debug mode and run it again?

Can you try this commit: aca864cfad54211f5b83b1844998214838b7373a

**Comment by Thomas-Ulrich** [comment]
yes Release mode. I can try the debug mode yes.
(sorry for some reason I missed the mail from github and I only see it now).
Do you want me to try the Doxygen generation?

**Comment by ravil-mobile** [comment]
> yes Release mode. I can try the debug mode yes.
Yes, please. Im pretty sure that you would see correct results with the Debug mode.

> Do you want me to try the Doxygen generation?

it would be nice as well.

**Comment by Thomas-Ulrich** [comment]
**hdf5, float**

fault: ok
surface: wrong
wavefield: ok
plasticity: ok

geometry array:
fault:  wrong
surface: ok
wavefield: ok
plasticity: ok

**posix, float**

data:
fault:  ok
surface: wrong
wavefield: wrong
plasticity: wrong

geometry array:
fault:  wrong
surface: ok
wavefield: ok
plasticity: ok

To test, I use a script which compute the min and max of the file at each time step, see below:
```
Reference, double:

di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> python TuSeisSolScripts/onHdf5/minmaxHdf5.py output_Sulawesi/$prefix-fault.xdmf --idt -1 --Data ASl
0 0.0 0.0
1 9.996516033367555e-18 2.156057099861127e-10
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4>
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> python TuSeisSolScripts/onHdf5/minmaxHdf5.py output_Sulawesi/$prefix-surface.xdmf --idt -1 --Data u
0 0.0 0.0
1 -1.6095860431691954e-10 1.5664228583209896e-10
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4>
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> python TuSeisSolScripts/onHdf5/minmaxHdf5.py output_Sulawesi/$prefix.xdmf --idt -1 --Data u
0 0.0 0.0
1 -8.843624624043142e-10 5.603538943530014e-10
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4>
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> python TuSeisSolScripts/onHdf5/minmaxHdf5.py output_Sulawesi/$prefix-low.xdmf --idt -1 --Data eta
0 0.0 0.0
1 0.0 0.0

-----

hdf5, float :

di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> export prefix=a2_01s
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4>
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> python TuSeisSolScripts/onHdf5/minmaxHdf5.py output_Sulawesi/$prefix-fault.xdmf --idt -1 --Data ASl
0 0.0 0.0
1 9.996516e-18 2.1560571e-10
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4>
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> python TuSeisSolScripts/onHdf5/minmaxHdf5.py output_Sulawesi/$prefix-surface.xdmf --idt -1 --Data u
0 0.0 0.0
1 -3.689349e+19 3.689349e+19
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4>
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> python TuSeisSolScripts/onHdf5/minmaxHdf5.py output_Sulawesi/$prefix.xdmf --idt -1 --Data u
0 0.0 0.0
1 -8.86551e-10 5.616609e-10
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4>
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> python TuSeisSolScripts/onHdf5/minmaxHdf5.py output_Sulawesi/$prefix-low.xdmf --idt -1 --Data eta
0 0.0 0.0
1 0.0 0.0

---

posix, float:

di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> python TuSeisSolScripts/onHdf5/minmaxHdf5.py output_Sulawesi/$prefix-fault.xdmf --idt -1 --Data ASl
0 0.0 0.0
1 9.996516e-18 2.1560571e-10
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4>
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> python TuSeisSolScripts/onHdf5/minmaxHdf5.py output_Sulawesi/$prefix-surface.xdmf --idt -1 --Data u
0 -168915.46875 1612133.9375
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4>
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> python TuSeisSolScripts/onHdf5/minmaxHdf5.py output_Sulawesi/$prefix.xdmf --idt -1 --Data u
0 -1.804341119680758e-75 2.633400168683509e-77
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4>
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> python TuSeisSolScripts/onHdf5/minmaxHdf5.py output_Sulawesi/$prefix-low.xdmf --idt -1 --Data eta
0 -22651.092644950568 1429947.4049622067
```

**Comment by ravil-mobile** [comment]
thanks for the info. I'll will debug further. However, there is something fishy with the Release mode

**Comment by Thomas-Ulrich** [comment]
I did one run with debug and got same resutls.

Concerning doxygen, I get a lot of these errors:
```
error: Problems running dot: exit code=127, command='dot', arguments='"/home/ulrich/test/figures/trash2/SeisSol/SourceCodeDocs/docs/html/inherit_graph_116.dot" -Tpng -o "/home/ulrich/test/figures/trash2/SeisSol/SourceCodeDocs/docs/html/inherit_graph_116.png" -Tcmapx -o "/home/ulrich/test/figures/trash2/SeisSol/SourceCodeDocs/docs/html/inherit_graph_116.map"'
sh: 1: dot: not found
```
and this ends up with:
```
error: problems opening map file /home/ulrich/test/figures/trash2/SeisSol/SourceCodeDocs/docs/html/Backend_8cpp__incl.map for inclusion in the docs!
If you installed Graphviz/dot after a previous failing run, 
try deleting the output directory and rerun doxygen.
error: problem writing FIG 0 figure!
```

**Comment by ravil-mobile** [comment]
Do you have graphviz installed on your system? 

If not, you can execute
sudo apt-get install graphviz

**Comment by ravil-mobile** [comment]
> I did one run with debug and got same resutls.

Could you, please, clone the latest SeisSol master branch and run with double precision and the Release mode, and try to output the same variables? It seems to me that a bug could be in the master branch as well.

**Comment by Thomas-Ulrich** [comment]
Here is the output for the master branch, double precision:
```
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> python TuSeisSolScripts/onHdf5/minmaxHdf5.py output_Sulawesi/$prefix-fault.xdmf --idt -1 --Data ASl
0 0.0 0.0
1 7.630844946330046e-20 0.19052526028050382
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> 
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> python TuSeisSolScripts/onHdf5/minmaxHdf5.py output_Sulawesi/$prefix-surface.xdmf --idt -1 --Data u
0 0.0 0.0
1 -4.230587858668136 5.092003170710125
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> 
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> python TuSeisSolScripts/onHdf5/minmaxHdf5.py output_Sulawesi/$prefix.xdmf --idt -1 --Data u
0 0.0 0.0
1 -4.1276451016799145 4.738974077984999
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> 
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4> python TuSeisSolScripts/onHdf5/minmaxHdf5.py output_Sulawesi/$prefix-low.xdmf --idt -1 --Data eta
0 0.0 0.0
1 0.0 4.688708901796001e-05
```
Indeed on your branch, even the double precision results are actually wrong.

---
Good that my OS is freshly installed. this shows all the dependencies.
For example you also need latex for generating the documentation:

```sh: 1: latex: not found
error: Problems running latex. Check your installation or look for typos in _formulas.tex and check _formulas.log!
sh: 1: dvips: not found
error: Problems running dvips. Check your installation!
error: Could not read image `/home/ulrich/test/figures/trash2/SeisSol/SourceCodeDocs/docs/html/classseissol_1_1kernels_1_1DirichletBoundary_a90e1e9430f44cc3a2bda08383037bf3b_cgraph.png' generated by dot!
```
So I suggest adding 
```
#apt-get install graphviz texlive-latex-extra 
```
to your doc.
Else it seems to work.

**Comment by ravil-mobile** [comment]
> So I suggest adding

Yep. There used to be a README for SourceCodeDocs. Unfortunately, it disappeared after I reverted Sebastian's changes. It will be done.

**Comment by ravil-mobile** [comment]
fixed by #315

**Pull request closed without merging**
