### PR TITLE
slip and aging laws

### PR DESCRIPTION
**Pull request by Thomas-Ulrich**
This is work in collaboration with Kadek.
This PR merges the slip and aging laws with the already existing strong velocity weakening rate and state.
It also introduces a fix to prevent negative state variables (also slip in LSW), that could arise due to the resampling matrix approach. Without the fix, NaN arises after some time in slip and aging laws.
So far, I've quickly tested that it runs and gives reasonable levels of slip.
A proper benchmarking is still pending, but I think the code can already be reviewed.

### CODE REVIEW

**Comment by AliceGabriel** [comment]
This pull request needs to be verified with SCEC benchmark tpv101/102(ageing law) https://strike.scec.org/cvws/download/SCEC_validation_ageing_law.pdf

**Comment by AliceGabriel** [comment]
See also section 7.1 in our GMD paper https://gmd.copernicus.org/articles/7/847/2014/gmd-7-847-2014.pdf

**Comment by AliceGabriel** [comment]
image

**Comment by AliceGabriel** [comment]
see also comparable implementations in PyLith https://geodynamics.org/cig/doxygen/release/pylith/_rate_state_ageing_8py_source.html 
or Sem2dpack https://github.com/jpampuero/sem2dpack/blob/master/SRC/bc_dynflt_rsf.f90 , etc

**Comment by Thomas-Ulrich** [comment]
Just to precise, I think the numerics should not be changed compared to how it was implemented before, as the update scheme used is the one of the fast velocity weakening law.
(which has been itself improved as we use more iterations and check for convergence instead of using 5 iterations).
Also, there is the projection to the modal basis function, which reduces the creeping artifact.
I agree that it should be tested with the scec benchmark. Actually, I thought it would work from scratch, given that it is based on tpv103, but then Kadek realized it is not working as expected (output not comparable with other codes), so I converted to draft the PR.
Anyway, any person willing to check the code is welcome.
Unfortunately, I cannot dedicate too much time right now to find the problem, but a comparison with specfem or Sem2dpack may help.

**Comment by palgunadi1993** [comment]
Hi All,

I think I've solved the problem. So, I followed sem2Dpack and make an absolute value for slip-rate on the calculation of state-variable. The main problem that gives NaN value is the multiplication matrix on the state variable with the resampling matrix. I think for the conventional ageing law and slip law we do not need this. 

here is my change w.r.t the git version c83b4e55066aa3b9062baa3fb252801265261b52
```
diff --git a/src/Physics/Evaluate_friction_law.f90 b/src/Physics/Evaluate_friction_law.f90
index f8a3c645..6cbeec97 100644
--- a/src/Physics/Evaluate_friction_law.f90
+++ b/src/Physics/Evaluate_friction_law.f90
@@ -968,7 +968,7 @@ MODULE Eval_friction_law_mod
              LocSR=ABS(SRtest)
              !update LocMu
              tmp = 0.5D0/RS_sr0 * EXP(LocSV/RS_a)
-             tmp2 = LocSR*tmp
+             tmp2 = ABS(LocSR)*tmp
              ! mu from LocSR
              LocMu  = RS_a*LOG(tmp2+SQRT(tmp2**2+1.0D0))
          ENDDO !  j=1,nSVupdates   !This loop corrects SV values
@@ -1007,7 +1007,7 @@ MODULE Eval_friction_law_mod
          ELSE
             tmp = 0.5D0/RS_sr0*EXP((RS_f0 + RS_b*LOG(RS_sr0*LocSV/RS_sl0))/RS_a)
          ENDIF
-         tmp2 = LocSR*tmp
+         tmp2 = ABS(LocSR)*tmp
          ! mu from LocSR
          LocMu  = RS_a*LOG(tmp2+SQRT(tmp2**2+1.0D0))

@@ -1071,7 +1071,11 @@ MODULE Eval_friction_law_mod
      DISC%DynRup%Slip2(:,iFace)     = LocSlip2
      DISC%DynRup%TracXY(:,iFace)    = LocTracXY
      DISC%DynRup%TracXZ(:,iFace)    = LocTracXZ
-     DISC%DynRup%StateVar(:,iFace)  = max(0.0, DISC%DynRup%StateVar(:,iFace) + matmul(resampleMatrix, LocSV - DISC%DynRup%StateVar(:,iFace)))
+     IF (EQN%FL.EQ.103) THEN
+         DISC%DynRup%StateVar(:,iFace)  = DISC%DynRup%StateVar(:,iFace) + matmul(resampleMatrix, LocSV - DISC%DynRup%StateVar(:,iFace))
+     ELSE
+         DISC%DynRup%StateVar(:,iFace)  = LocSV
+     ENDIF

      IF (DISC%DynRup%magnitude_out(iFace)) THEN
         DISC%DynRup%averaged_Slip(iFace) = DISC%DynRup%averaged_Slip(iFace) + sum(tmpSlip)/nBndGP
@@ -1088,8 +1092,9 @@ MODULE Eval_friction_law_mod
     ! Argument list declaration
     INTEGER                  :: iFace, nBndGP
     REAL                     :: RS_f0, RS_b, RS_a(nBndGP), RS_sr0, RS_fw, RS_srW(nBndGP), RS_sl0(nBndGP) !constant input parameters
-    REAL                     :: SV0(nBndGP), time_inc, SR_tmp(nBndGP)                  !changing during iterations
-    REAL                     :: flv(nBndGP), fss(nBndGP), SVss(nBndGP), LocSV(nBndGP)                 !calculated in this routine
+    REAL                     :: SV0(nBndGP), time_inc, SR_tmp(nBndGP)        !changing during iterations
+    REAL                     :: flv(nBndGP), fss(nBndGP), SVss(nBndGP), LocSV(nBndGP)          !calculated in this routine
+    !REAL                     :: AlmostZero = 1e-5
     !-------------------------------------------------------------------------!
     INTENT(IN)    :: EQN, DISC, iFace, nBndGP, SV0, time_inc, SR_tmp
     INTENT(INOUT) :: LocSV
@@ -1107,9 +1112,9 @@ MODULE Eval_friction_law_mod

     SELECT CASE(EQN%FL)
     CASE(3)
-        LocSV = SV0*EXP(-SR_tmp*time_inc/RS_sl0) + RS_sl0/SR_tmp*(1.0 - EXP(-SR_tmp*time_inc/RS_sl0))
+        LocSV = SV0*EXP(-ABS(SR_tmp)*time_inc/RS_sl0) + RS_sl0/ABS(SR_tmp)*(1.0 - EXP(-ABS(SR_tmp)*time_inc/RS_sl0))
     CASE(4)
-        LocSV = RS_sl0/SR_tmp*(SR_tmp*SV0/RS_sl0)**(EXP(-SR_tmp*time_inc/RS_sl0))
+        LocSV = RS_sl0/ABS(SR_tmp)*(ABS(SR_tmp)*SV0/RS_sl0)**(EXP(-ABS(SR_tmp)*time_inc/RS_sl0))
     CASE(103)
         ! low-velocity steady state friction coefficient
         flv = RS_f0 - (RS_b-RS_a)* LOG(SR_tmp/RS_sr0)
@@ -1171,7 +1176,7 @@ MODULE Eval_friction_law_mod
     RS_b   = DISC%DynRup%RS_b       ! b, evolution effect
     RS_sl0 = DISC%DynRup%RS_sl0_array(:,iFace)     ! L, char. length scale

-    SRtest = LocSR
+    SRtest = ABS(LocSR)

     IF(EQN%FL.EQ.103) THEN
        tmp   =  0.5D0 / RS_sr0 *EXP (LocSV/RS_a)
```

**Comment by Thomas-Ulrich** [comment]
Hi,

I think that most of the changes you propose are not necessary because SR is positive due to this line:
https://github.com/SeisSol/SeisSol/blob/c83b4e55066aa3b9062baa3fb252801265261b52/src/Physics/Evaluate_friction_law.f90#L1207
Therefore, the problem is this only line:

https://github.com/SeisSol/SeisSol/blob/kadek/fix_101/src/Physics/Evaluate_friction_law.f90#L1074

Either because of the max(0, or the resampling.
which would not work with with FL=3. Do you agree?

Thomas

**Comment by palgunadi1993** [comment]
Hi Thomas,

Yes, I agree. That's the only thing that matters if the SR_tmp is always positive.

Kadek

**Comment by palgunadi1993** [comment]
Hi, 

TPV102 and TPV104 are matched with Kaneko (SPECFEM3D) using this branch. So, merging FL.103 and FL.3/FL.4 works fine.
The remaining problem for friction law 3 (RS ageing law) and 4 (RS slip law) is creeping slip (how to stop the rupture?).
The current implementation of the resampling matrix still does not work.

Best regards,
Kadek

**Comment by Thomas-Ulrich** [comment]
Hi, tpv101 and 103 are validated and working. I've also updated the documentation.
Please review!

**Review by palgunadi1993 — APPROVED** [review]
I approved the changes

**Pull request merged**
