### PR TITLE
Remove check for invertability

### PR DESCRIPTION
**Pull request by sebwolf-de**

### CODE REVIEW

**Comment by uphoffc** [comment]
??

**Comment by uphoffc** [comment]
Is the issue fixed or what??

**Comment by Thomas-Ulrich** [comment]
I think there is an underlying issue.
See my edit on the penultimate comment of this issue:
https://github.com/SeisSol/SeisSol/issues/140

**Comment by sebwolf-de** [comment]
We compared the old implementation e599e8b with the one implemented here. We used all materials given by Thomas' Korea setup and calculated the Godunov States. The solutions with the inverse compared to the old one has an error of 10^-{16}.

**Comment by uphoffc** [comment]
Ah ok. Is now an SVD or something like that used to invert the matrix?

**Comment by sebwolf-de** [comment]
[matrix.tar.gz](https://github.com/SeisSol/SeisSol/files/4191378/matrix.tar.gz)

**Comment by sebwolf-de** [comment]
We leave it to the Eigen internals to decide what they use. Talk to you after lunch ;-)

**Comment by Thomas-Ulrich** [comment]
Hi,
I just run Kadek's setup and it does not crash and produces outputs that looks ok.

**Comment by krenzland** [comment]
> Ah ok. Is now an SVD or something like that used to invert the matrix?

It's LU according to the documentation

**Pull request merged**
