### PR TITLE
Add TP parameters to documentation

### PR DESCRIPTION
**Pull request by sebanger**

### CODE REVIEW

**Comment by sebwolf-de** [comment]
Thanks for the update.
I have some more general concerns about the documentary. In the code snippet, there is the OutputMask array, in the text we talk about the iOutputMask. Additionally there is a malformatted U_n. 
Maybe you could fix these on the way ;-)

**Comment by sebwolf-de** [comment]
For the namelists "Pickpoint" and "Elementwise" the parameter is called OutputMask.
For the namelist "Output" the parameter is called iOutputMask. 
So for this context we just need to talk about OutputMask.

**Comment by sebanger** [comment]
> 
> 
> For the namelists "Pickpoint" and "Elementwise" the parameter is called OutputMask.
> For the namelist "Output" the parameter is called iOutputMask.
> So for this context we just need to talk about OutputMask.

should fix this now

**Comment by sebwolf-de** [comment]
Anyway, is it a good idea to merge this now, when the TP branch has not been merged.

**Comment by sebanger** [comment]
The TP branch should be merged by end of next week. So the documentation can be already merged

**Pull request merged**
