### PR TITLE
Thomas/extract data

### PR DESCRIPTION
**Pull request by Thomas-Ulrich**
The script extractDataFromUnstructuredOutput.py allows to extract specific data from a seissol output file.
For example, if you want to extract time steps 10 and 12 of file Sul8e6_straight_short-surface.xdmf and variables u and w, and convert the output to float, you can execute:

```
python extractDataFromUnstructuredOutput.py Sul8e6_straight_short-surface.xdmf --Data u w --idt 10 12 --float
```
output:
```
done writing Sul8e6_straight_short_resampled-surface_vertex/mesh0/geometry.bin
done writing Sul8e6_straight_short_resampled-surface_cell/mesh0/connect.bin
done writing Sul8e6_straight_short_resampled-surface_cell/mesh0/u.bin
done writing Sul8e6_straight_short_resampled-surface_cell/mesh0/w.bin
done writing Sul8e6_straight_short_resampled-surface.xdmf
```
This can be also used to transform a seissol file in posix format to hdf5, and vice versa.
This scripts uses a script (recreateXdmf.py) able to recreate a xdmf file (which can itself be used alone, e.g. to recover a backup file).

Also I ve updated the references to my pythonXdmfReader, as someone remove the `__init__.py` file  that I used to access this module.

### CODE REVIEW

**Comment by Thomas-Ulrich** [comment]
this is ready for review

**Comment by Thomas-Ulrich** [comment]
Hi,
Could this pull request be reviewed or at least validated?
Thomas.

**Comment by sebwolf-de** [comment]
Hi, 
I wanted to test the scripts by myself, but I did not find the time yet. Sorry for that.
If you have tested these scripts before, I see no problem with merging.
Best,
Sebastian

**Comment by AliceGabriel** [comment]
I approve too. Aniko ran the scripts and can comment if required.

**Pull request merged**
