### PR TITLE
Fix read the docs build

### PR DESCRIPTION
**Pull request by uphoffc**

### CODE REVIEW

**Comment by krenzland** [comment]
This makes sense but is caused by a missing dependecy in sphinx: https://github.com/sphinx-doc/sphinx/issues/10927
Wouldn't it make more sense to upgrade to a more recent sphinx version or would this break our documentation?

**Comment by uphoffc** [comment]
No, the issue is the release of urllib3 on May 4th:

"ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168"

**Comment by krenzland** [comment]
Okay, cool. Then, I think, we could remove the urllib dependency as it should be included by the requirements of sphinx (via requests). We can also leave it in, it doesn't hurt probably

**Review by krenzland — APPROVED** [review]

**Comment by uphoffc** [comment]
It might still be necessary as the requests package could install urllib3 >= 2 and then the problem reappears.

**Pull request merged**
