### PR TITLE
Use FindPython3 to find python3

### PR DESCRIPTION
**Pull request by krenzland**
Fixes compilation on some systems e.g. Isembard.

### CODE REVIEW

**Comment by krenzland** [comment]
@ravil-mobile Any idea why this would break the GPU pipeline? There is some issue with pybind that I cannot explain- but it looks like it's genuinely broken. But the CPU pipeline works, which should use a similar setting for pybind, right?

**Comment by Thomas-Ulrich** [comment]
Could it be because of ```python3_add_library`` instead of ```Python3_add_library```?
(https://cmake.org/cmake/help/latest/module/FindPython3.html)

**Comment by krenzland** [comment]
Thanks, but CMake is case insensitive. The problem was rather that pybind needs the DEVELOPMENT components of Python3 but if we call find_package(Python3 ...) without specifying the development component, the find_package call in Pybind does not include DEVELOPMENT either

**Review by Thomas-Ulrich — APPROVED** [review]
LGTM

**Pull request merged**
