### PR TITLE
Fix typo in metis comp.

### PR DESCRIPTION
**Pull request by krenzland**

### CODE REVIEW

**Comment by Thomas-Ulrich** [comment]
well I guess it depends on the compiler name. 
e.g. using mpi.ibm, it is called mpicc.
So for me it is not a typo.

**Comment by krenzland** [comment]
That's a good point, but shouldn't it be mpicc instead of mpiCC then?

**Comment by Thomas-Ulrich** [comment]
mpicc for c files and mpiCC for cpp files?

**Comment by krenzland** [comment]
Ah, you're right.
Apparently it's been a long time since I've compiled on phase 2 ;)

I think we should change this to use ${CC} ${CXX} environment variables in the future but I'll close this for now.

**Pull request closed without merging**
