### PR TITLE
Specify iterator type explicitly

### PR DESCRIPTION
**Pull request by davschneller**
Related to #1209 .

The question would be: would we want to merge it—or request everyone to just use a newer compiler?

Hence draft for now; may be closed.

### CODE REVIEW

**Comment by Thomas-Ulrich** [comment]
thank you. At least with spack, we can make a patch

**Comment by davschneller** [comment]
If it's still in 2023.2, we can also merge that one here; the code change is pretty tiny after all.

**Comment by Thomas-Ulrich** [comment]
ok, I give it a try, and if it works, I will merge.

**Review by Thomas-Ulrich — APPROVED** [review]
works!

**Pull request merged**
